[package]
name = "battery_threshold"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk = { git = "https://github.com/gtk-rs/gtk4-rs.git", package = "gtk4" }
# gtk = { version = "0.5.5", package = "gtk4" }
