[package]
name = "battery_threshold"
version = "0.3.0"
edition = "2021"

[dependencies]
glib = "0.20.9"
gtk = { version = "0.9.6", package = "gtk4", features = ["v4_18"] }
# gtk4 = "0.9.6"
# gtk = { git = "https://github.com/gtk-rs/gtk4-rs.git", package = "gtk4", features = [
#   "v4_16",
# ] }

# [dependencies.gtk]
# package = "gtk4"
# version = "0.9.6"
# features = ["v4_18"]
